//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Noord.Hollands.Archief.Preingest.WebApi.Entities.ToPX.v2_2 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    [System.Xml.Serialization.XmlRootAttribute("ToPX", Namespace="http://www.nationaalarchief.nl/ToPX/v2.2", IsNullable=false)]
    public partial class topxType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aggregatie", typeof(aggregatieType))]
        [System.Xml.Serialization.XmlElementAttribute("bestand", typeof(bestandType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class aggregatieType {
        
        private string identificatiekenmerkField;
        
        private aggregatieAggregatieniveauType aggregatieniveauField;
        
        private typedNonEmptyStringType[] naamField;
        
        private classificatieType[] classificatieField;
        
        private typedStringType[] omschrijvingField;
        
        private string plaatsField;
        
        private dekkingType[] dekkingField;
        
        private externIdentificatiekenmerkType[] externIdentificatiekenmerkField;
        
        private taalType[] taalField;
        
        private eventGeschiedenisType[] eventGeschiedenisField;
        
        private eventPlanType[] eventPlanField;
        
        private relatieType[] relatieField;
        
        private contextType contextField;
        
        private gebruiksrechtenType[] gebruiksrechtenField;
        
        private vertrouwelijkheidType[] vertrouwelijkheidField;
        
        private openbaarheidType[] openbaarheidField;
        
        private string integriteitField;
        
        private System.Xml.XmlElement generiekeMetadataField;
        
        /// <remarks/>
        public string identificatiekenmerk {
            get {
                return this.identificatiekenmerkField;
            }
            set {
                this.identificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        public aggregatieAggregatieniveauType aggregatieniveau {
            get {
                return this.aggregatieniveauField;
            }
            set {
                this.aggregatieniveauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("naam")]
        public typedNonEmptyStringType[] naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificatie")]
        public classificatieType[] classificatie {
            get {
                return this.classificatieField;
            }
            set {
                this.classificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("omschrijving")]
        public typedStringType[] omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dekking")]
        public dekkingType[] dekking {
            get {
                return this.dekkingField;
            }
            set {
                this.dekkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("externIdentificatiekenmerk")]
        public externIdentificatiekenmerkType[] externIdentificatiekenmerk {
            get {
                return this.externIdentificatiekenmerkField;
            }
            set {
                this.externIdentificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taal")]
        public taalType[] taal {
            get {
                return this.taalField;
            }
            set {
                this.taalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventGeschiedenis")]
        public eventGeschiedenisType[] eventGeschiedenis {
            get {
                return this.eventGeschiedenisField;
            }
            set {
                this.eventGeschiedenisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventPlan")]
        public eventPlanType[] eventPlan {
            get {
                return this.eventPlanField;
            }
            set {
                this.eventPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatie")]
        public relatieType[] relatie {
            get {
                return this.relatieField;
            }
            set {
                this.relatieField = value;
            }
        }
        
        /// <remarks/>
        public contextType context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gebruiksrechten")]
        public gebruiksrechtenType[] gebruiksrechten {
            get {
                return this.gebruiksrechtenField;
            }
            set {
                this.gebruiksrechtenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vertrouwelijkheid")]
        public vertrouwelijkheidType[] vertrouwelijkheid {
            get {
                return this.vertrouwelijkheidField;
            }
            set {
                this.vertrouwelijkheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("openbaarheid")]
        public openbaarheidType[] openbaarheid {
            get {
                return this.openbaarheidField;
            }
            set {
                this.openbaarheidField = value;
            }
        }
        
        /// <remarks/>
        public string integriteit {
            get {
                return this.integriteitField;
            }
            set {
                this.integriteitField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement generiekeMetadata {
            get {
                return this.generiekeMetadataField;
            }
            set {
                this.generiekeMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public enum aggregatieAggregatieniveauType {
        
        /// <remarks/>
        Record,
        
        /// <remarks/>
        Dossier,
        
        /// <remarks/>
        Serie,
        
        /// <remarks/>
        Archief,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class typedNonEmptyStringType {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class formaatEventPlanType {
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        private string typeField;
        
        private string beschrijvingField;
        
        private string aanleidingField;
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string beschrijving {
            get {
                return this.beschrijvingField;
            }
            set {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string aanleiding {
            get {
                return this.aanleidingField;
            }
            set {
                this.aanleidingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class datumOfPeriodeType {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datum", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("datumEnTijd", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("jaar", typeof(string), DataType="gYear")]
        [System.Xml.Serialization.XmlElementAttribute("periode", typeof(periodeType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class periodeType {
        
        private datumOfJaarType beginField;
        
        private datumOfJaarType eindField;
        
        /// <remarks/>
        public datumOfJaarType begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public datumOfJaarType eind {
            get {
                return this.eindField;
            }
            set {
                this.eindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class datumOfJaarType {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datum", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("datumEnTijd", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("jaar", typeof(string), DataType="gYear")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        datum,
        
        /// <remarks/>
        datumEnTijd,
        
        /// <remarks/>
        jaar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        datum,
        
        /// <remarks/>
        datumEnTijd,
        
        /// <remarks/>
        jaar,
        
        /// <remarks/>
        periode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class fysiekeIntegriteitType {
        
        private string algoritmeField;
        
        private string waardeField;
        
        private System.DateTime datumEnTijdField;
        
        /// <remarks/>
        public string algoritme {
            get {
                return this.algoritmeField;
            }
            set {
                this.algoritmeField = value;
            }
        }
        
        /// <remarks/>
        public string waarde {
            get {
                return this.waardeField;
            }
            set {
                this.waardeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime datumEnTijd {
            get {
                return this.datumEnTijdField;
            }
            set {
                this.datumEnTijdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class creatieApplicatieType {
        
        private string naamField;
        
        private string versieField;
        
        private string datumAanmaakField;
        
        /// <remarks/>
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        public string versie {
            get {
                return this.versieField;
            }
            set {
                this.versieField = value;
            }
        }
        
        /// <remarks/>
        public string datumAanmaak {
            get {
                return this.datumAanmaakField;
            }
            set {
                this.datumAanmaakField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class bestandsnaamType {
        
        private string naamField;
        
        private string extensieField;
        
        /// <remarks/>
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        public string extensie {
            get {
                return this.extensieField;
            }
            set {
                this.extensieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class formaatType {
        
        private string identificatiekenmerkField;
        
        private bestandsnaamType bestandsnaamField;
        
        private string typeField;
        
        private string omvangField;
        
        private string bestandsformaatField;
        
        private creatieApplicatieType creatieapplicatieField;
        
        private fysiekeIntegriteitType fysiekeIntegriteitField;
        
        private string datumAanmaakField;
        
        private formaatEventPlanType[] eventPlanField;
        
        private string[] relatieField;
        
        /// <remarks/>
        public string identificatiekenmerk {
            get {
                return this.identificatiekenmerkField;
            }
            set {
                this.identificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        public bestandsnaamType bestandsnaam {
            get {
                return this.bestandsnaamField;
            }
            set {
                this.bestandsnaamField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string omvang {
            get {
                return this.omvangField;
            }
            set {
                this.omvangField = value;
            }
        }
        
        /// <remarks/>
        public string bestandsformaat {
            get {
                return this.bestandsformaatField;
            }
            set {
                this.bestandsformaatField = value;
            }
        }
        
        /// <remarks/>
        public creatieApplicatieType creatieapplicatie {
            get {
                return this.creatieapplicatieField;
            }
            set {
                this.creatieapplicatieField = value;
            }
        }
        
        /// <remarks/>
        public fysiekeIntegriteitType fysiekeIntegriteit {
            get {
                return this.fysiekeIntegriteitField;
            }
            set {
                this.fysiekeIntegriteitField = value;
            }
        }
        
        /// <remarks/>
        public string datumAanmaak {
            get {
                return this.datumAanmaakField;
            }
            set {
                this.datumAanmaakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventPlan")]
        public formaatEventPlanType[] eventPlan {
            get {
                return this.eventPlanField;
            }
            set {
                this.eventPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatie")]
        public string[] relatie {
            get {
                return this.relatieField;
            }
            set {
                this.relatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class vormType {
        
        private string redactieGenreField;
        
        private string[] verschijningsvormField;
        
        private string structuurField;
        
        /// <remarks/>
        public string redactieGenre {
            get {
                return this.redactieGenreField;
            }
            set {
                this.redactieGenreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("verschijningsvorm")]
        public string[] verschijningsvorm {
            get {
                return this.verschijningsvormField;
            }
            set {
                this.verschijningsvormField = value;
            }
        }
        
        /// <remarks/>
        public string structuur {
            get {
                return this.structuurField;
            }
            set {
                this.structuurField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class bestandType {
        
        private string identificatiekenmerkField;
        
        private bestandAggregatieniveauType aggregatieniveauField;
        
        private typedNonEmptyStringType[] naamField;
        
        private classificatieType[] classificatieField;
        
        private typedStringType[] omschrijvingField;
        
        private string plaatsField;
        
        private dekkingType[] dekkingField;
        
        private externIdentificatiekenmerkType[] externIdentificatiekenmerkField;
        
        private taalType[] taalField;
        
        private eventGeschiedenisType[] eventGeschiedenisField;
        
        private eventPlanType[] eventPlanField;
        
        private relatieType[] relatieField;
        
        private contextType contextField;
        
        private gebruiksrechtenType[] gebruiksrechtenField;
        
        private vertrouwelijkheidType[] vertrouwelijkheidField;
        
        private openbaarheidType[] openbaarheidField;
        
        private vormType vormField;
        
        private string integriteitField;
        
        private formaatType[] formaatField;
        
        private System.Xml.XmlElement generiekeMetadataField;
        
        /// <remarks/>
        public string identificatiekenmerk {
            get {
                return this.identificatiekenmerkField;
            }
            set {
                this.identificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        public bestandAggregatieniveauType aggregatieniveau {
            get {
                return this.aggregatieniveauField;
            }
            set {
                this.aggregatieniveauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("naam")]
        public typedNonEmptyStringType[] naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificatie")]
        public classificatieType[] classificatie {
            get {
                return this.classificatieField;
            }
            set {
                this.classificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("omschrijving")]
        public typedStringType[] omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dekking")]
        public dekkingType[] dekking {
            get {
                return this.dekkingField;
            }
            set {
                this.dekkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("externIdentificatiekenmerk")]
        public externIdentificatiekenmerkType[] externIdentificatiekenmerk {
            get {
                return this.externIdentificatiekenmerkField;
            }
            set {
                this.externIdentificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taal")]
        public taalType[] taal {
            get {
                return this.taalField;
            }
            set {
                this.taalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventGeschiedenis")]
        public eventGeschiedenisType[] eventGeschiedenis {
            get {
                return this.eventGeschiedenisField;
            }
            set {
                this.eventGeschiedenisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventPlan")]
        public eventPlanType[] eventPlan {
            get {
                return this.eventPlanField;
            }
            set {
                this.eventPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatie")]
        public relatieType[] relatie {
            get {
                return this.relatieField;
            }
            set {
                this.relatieField = value;
            }
        }
        
        /// <remarks/>
        public contextType context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gebruiksrechten")]
        public gebruiksrechtenType[] gebruiksrechten {
            get {
                return this.gebruiksrechtenField;
            }
            set {
                this.gebruiksrechtenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vertrouwelijkheid")]
        public vertrouwelijkheidType[] vertrouwelijkheid {
            get {
                return this.vertrouwelijkheidField;
            }
            set {
                this.vertrouwelijkheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("openbaarheid")]
        public openbaarheidType[] openbaarheid {
            get {
                return this.openbaarheidField;
            }
            set {
                this.openbaarheidField = value;
            }
        }
        
        /// <remarks/>
        public vormType vorm {
            get {
                return this.vormField;
            }
            set {
                this.vormField = value;
            }
        }
        
        /// <remarks/>
        public string integriteit {
            get {
                return this.integriteitField;
            }
            set {
                this.integriteitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formaat")]
        public formaatType[] formaat {
            get {
                return this.formaatField;
            }
            set {
                this.formaatField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement generiekeMetadata {
            get {
                return this.generiekeMetadataField;
            }
            set {
                this.generiekeMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public enum bestandAggregatieniveauType {
        
        /// <remarks/>
        Bestand,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class classificatieType {
        
        private string codeField;
        
        private string omschrijvingField;
        
        private string bronField;
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string bron {
            get {
                return this.bronField;
            }
            set {
                this.bronField = value;
            }
        }
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class typedStringType {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class dekkingType {
        
        private periodeType inTijdField;
        
        private string[] geografischGebiedField;
        
        /// <remarks/>
        public periodeType inTijd {
            get {
                return this.inTijdField;
            }
            set {
                this.inTijdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("geografischGebied")]
        public string[] geografischGebied {
            get {
                return this.geografischGebiedField;
            }
            set {
                this.geografischGebiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class externIdentificatiekenmerkType {
        
        private string kenmerkSysteemField;
        
        private string nummerBinnenSysteemField;
        
        /// <remarks/>
        public string kenmerkSysteem {
            get {
                return this.kenmerkSysteemField;
            }
            set {
                this.kenmerkSysteemField = value;
            }
        }
        
        /// <remarks/>
        public string nummerBinnenSysteem {
            get {
                return this.nummerBinnenSysteemField;
            }
            set {
                this.nummerBinnenSysteemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public enum taalType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
        
        /// <remarks/>
        aar,
        
        /// <remarks/>
        abk,
        
        /// <remarks/>
        ace,
        
        /// <remarks/>
        ach,
        
        /// <remarks/>
        ada,
        
        /// <remarks/>
        ady,
        
        /// <remarks/>
        afa,
        
        /// <remarks/>
        afh,
        
        /// <remarks/>
        afr,
        
        /// <remarks/>
        ain,
        
        /// <remarks/>
        aka,
        
        /// <remarks/>
        akk,
        
        /// <remarks/>
        alb,
        
        /// <remarks/>
        ale,
        
        /// <remarks/>
        alg,
        
        /// <remarks/>
        alt,
        
        /// <remarks/>
        amh,
        
        /// <remarks/>
        ang,
        
        /// <remarks/>
        anp,
        
        /// <remarks/>
        apa,
        
        /// <remarks/>
        ara,
        
        /// <remarks/>
        arc,
        
        /// <remarks/>
        arg,
        
        /// <remarks/>
        arm,
        
        /// <remarks/>
        arn,
        
        /// <remarks/>
        arp,
        
        /// <remarks/>
        art,
        
        /// <remarks/>
        arw,
        
        /// <remarks/>
        asm,
        
        /// <remarks/>
        ast,
        
        /// <remarks/>
        ath,
        
        /// <remarks/>
        aus,
        
        /// <remarks/>
        ava,
        
        /// <remarks/>
        ave,
        
        /// <remarks/>
        awa,
        
        /// <remarks/>
        aym,
        
        /// <remarks/>
        aze,
        
        /// <remarks/>
        bad,
        
        /// <remarks/>
        bai,
        
        /// <remarks/>
        bak,
        
        /// <remarks/>
        bal,
        
        /// <remarks/>
        bam,
        
        /// <remarks/>
        ban,
        
        /// <remarks/>
        baq,
        
        /// <remarks/>
        bas,
        
        /// <remarks/>
        bat,
        
        /// <remarks/>
        bej,
        
        /// <remarks/>
        bel,
        
        /// <remarks/>
        bem,
        
        /// <remarks/>
        ben,
        
        /// <remarks/>
        ber,
        
        /// <remarks/>
        bho,
        
        /// <remarks/>
        bih,
        
        /// <remarks/>
        bik,
        
        /// <remarks/>
        bin,
        
        /// <remarks/>
        bis,
        
        /// <remarks/>
        bla,
        
        /// <remarks/>
        bnt,
        
        /// <remarks/>
        bos,
        
        /// <remarks/>
        bra,
        
        /// <remarks/>
        bre,
        
        /// <remarks/>
        btk,
        
        /// <remarks/>
        bua,
        
        /// <remarks/>
        bug,
        
        /// <remarks/>
        bul,
        
        /// <remarks/>
        bur,
        
        /// <remarks/>
        byn,
        
        /// <remarks/>
        cad,
        
        /// <remarks/>
        cai,
        
        /// <remarks/>
        car,
        
        /// <remarks/>
        cat,
        
        /// <remarks/>
        cau,
        
        /// <remarks/>
        ceb,
        
        /// <remarks/>
        cel,
        
        /// <remarks/>
        cha,
        
        /// <remarks/>
        chb,
        
        /// <remarks/>
        che,
        
        /// <remarks/>
        chg,
        
        /// <remarks/>
        chi,
        
        /// <remarks/>
        chk,
        
        /// <remarks/>
        chm,
        
        /// <remarks/>
        chn,
        
        /// <remarks/>
        cho,
        
        /// <remarks/>
        chp,
        
        /// <remarks/>
        chr,
        
        /// <remarks/>
        chu,
        
        /// <remarks/>
        chv,
        
        /// <remarks/>
        chy,
        
        /// <remarks/>
        cmc,
        
        /// <remarks/>
        cop,
        
        /// <remarks/>
        cor,
        
        /// <remarks/>
        cos,
        
        /// <remarks/>
        cpe,
        
        /// <remarks/>
        cpf,
        
        /// <remarks/>
        cpp,
        
        /// <remarks/>
        cre,
        
        /// <remarks/>
        crh,
        
        /// <remarks/>
        crp,
        
        /// <remarks/>
        csb,
        
        /// <remarks/>
        cus,
        
        /// <remarks/>
        wel,
        
        /// <remarks/>
        cze,
        
        /// <remarks/>
        dak,
        
        /// <remarks/>
        dan,
        
        /// <remarks/>
        dar,
        
        /// <remarks/>
        day,
        
        /// <remarks/>
        del,
        
        /// <remarks/>
        den,
        
        /// <remarks/>
        ger,
        
        /// <remarks/>
        dgr,
        
        /// <remarks/>
        din,
        
        /// <remarks/>
        div,
        
        /// <remarks/>
        doi,
        
        /// <remarks/>
        dra,
        
        /// <remarks/>
        dsb,
        
        /// <remarks/>
        dua,
        
        /// <remarks/>
        dum,
        
        /// <remarks/>
        dut,
        
        /// <remarks/>
        dyu,
        
        /// <remarks/>
        dzo,
        
        /// <remarks/>
        efi,
        
        /// <remarks/>
        egy,
        
        /// <remarks/>
        eka,
        
        /// <remarks/>
        elx,
        
        /// <remarks/>
        eng,
        
        /// <remarks/>
        enm,
        
        /// <remarks/>
        epo,
        
        /// <remarks/>
        est,
        
        /// <remarks/>
        ewe,
        
        /// <remarks/>
        ewo,
        
        /// <remarks/>
        fan,
        
        /// <remarks/>
        fao,
        
        /// <remarks/>
        fat,
        
        /// <remarks/>
        fij,
        
        /// <remarks/>
        fil,
        
        /// <remarks/>
        fin,
        
        /// <remarks/>
        fiu,
        
        /// <remarks/>
        fon,
        
        /// <remarks/>
        fre,
        
        /// <remarks/>
        frm,
        
        /// <remarks/>
        fro,
        
        /// <remarks/>
        frr,
        
        /// <remarks/>
        frs,
        
        /// <remarks/>
        fry,
        
        /// <remarks/>
        ful,
        
        /// <remarks/>
        fur,
        
        /// <remarks/>
        gaa,
        
        /// <remarks/>
        gay,
        
        /// <remarks/>
        gba,
        
        /// <remarks/>
        gem,
        
        /// <remarks/>
        geo,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ger")]
        ger1,
        
        /// <remarks/>
        gez,
        
        /// <remarks/>
        gil,
        
        /// <remarks/>
        gla,
        
        /// <remarks/>
        gle,
        
        /// <remarks/>
        glg,
        
        /// <remarks/>
        glv,
        
        /// <remarks/>
        gmh,
        
        /// <remarks/>
        goh,
        
        /// <remarks/>
        gon,
        
        /// <remarks/>
        gor,
        
        /// <remarks/>
        got,
        
        /// <remarks/>
        grb,
        
        /// <remarks/>
        grc,
        
        /// <remarks/>
        gre,
        
        /// <remarks/>
        grn,
        
        /// <remarks/>
        gsw,
        
        /// <remarks/>
        guj,
        
        /// <remarks/>
        gwi,
        
        /// <remarks/>
        hai,
        
        /// <remarks/>
        hat,
        
        /// <remarks/>
        hau,
        
        /// <remarks/>
        haw,
        
        /// <remarks/>
        heb,
        
        /// <remarks/>
        her,
        
        /// <remarks/>
        hil,
        
        /// <remarks/>
        him,
        
        /// <remarks/>
        hin,
        
        /// <remarks/>
        hit,
        
        /// <remarks/>
        hmn,
        
        /// <remarks/>
        hmo,
        
        /// <remarks/>
        hrv,
        
        /// <remarks/>
        hsb,
        
        /// <remarks/>
        hun,
        
        /// <remarks/>
        hup,
        
        /// <remarks/>
        iba,
        
        /// <remarks/>
        ibo,
        
        /// <remarks/>
        ice,
        
        /// <remarks/>
        ido,
        
        /// <remarks/>
        iii,
        
        /// <remarks/>
        ijo,
        
        /// <remarks/>
        iku,
        
        /// <remarks/>
        ile,
        
        /// <remarks/>
        ilo,
        
        /// <remarks/>
        ina,
        
        /// <remarks/>
        inc,
        
        /// <remarks/>
        ind,
        
        /// <remarks/>
        ine,
        
        /// <remarks/>
        inh,
        
        /// <remarks/>
        ipk,
        
        /// <remarks/>
        ira,
        
        /// <remarks/>
        iro,
        
        /// <remarks/>
        ita,
        
        /// <remarks/>
        jav,
        
        /// <remarks/>
        jbo,
        
        /// <remarks/>
        jpn,
        
        /// <remarks/>
        jpr,
        
        /// <remarks/>
        jrb,
        
        /// <remarks/>
        kaa,
        
        /// <remarks/>
        kab,
        
        /// <remarks/>
        kac,
        
        /// <remarks/>
        kal,
        
        /// <remarks/>
        kam,
        
        /// <remarks/>
        kan,
        
        /// <remarks/>
        kar,
        
        /// <remarks/>
        kas,
        
        /// <remarks/>
        kau,
        
        /// <remarks/>
        kaw,
        
        /// <remarks/>
        kaz,
        
        /// <remarks/>
        kbd,
        
        /// <remarks/>
        kha,
        
        /// <remarks/>
        khi,
        
        /// <remarks/>
        khm,
        
        /// <remarks/>
        kho,
        
        /// <remarks/>
        kik,
        
        /// <remarks/>
        kin,
        
        /// <remarks/>
        kir,
        
        /// <remarks/>
        kmb,
        
        /// <remarks/>
        kok,
        
        /// <remarks/>
        kom,
        
        /// <remarks/>
        kon,
        
        /// <remarks/>
        kor,
        
        /// <remarks/>
        kos,
        
        /// <remarks/>
        kpe,
        
        /// <remarks/>
        krc,
        
        /// <remarks/>
        krl,
        
        /// <remarks/>
        kro,
        
        /// <remarks/>
        kru,
        
        /// <remarks/>
        kua,
        
        /// <remarks/>
        kum,
        
        /// <remarks/>
        kur,
        
        /// <remarks/>
        kut,
        
        /// <remarks/>
        lad,
        
        /// <remarks/>
        lah,
        
        /// <remarks/>
        lam,
        
        /// <remarks/>
        lao,
        
        /// <remarks/>
        lat,
        
        /// <remarks/>
        lav,
        
        /// <remarks/>
        lez,
        
        /// <remarks/>
        lim,
        
        /// <remarks/>
        lin,
        
        /// <remarks/>
        lit,
        
        /// <remarks/>
        lol,
        
        /// <remarks/>
        loz,
        
        /// <remarks/>
        ltz,
        
        /// <remarks/>
        lua,
        
        /// <remarks/>
        lub,
        
        /// <remarks/>
        lug,
        
        /// <remarks/>
        lui,
        
        /// <remarks/>
        lun,
        
        /// <remarks/>
        luo,
        
        /// <remarks/>
        lus,
        
        /// <remarks/>
        mac,
        
        /// <remarks/>
        mad,
        
        /// <remarks/>
        mag,
        
        /// <remarks/>
        mah,
        
        /// <remarks/>
        mai,
        
        /// <remarks/>
        mak,
        
        /// <remarks/>
        mal,
        
        /// <remarks/>
        man,
        
        /// <remarks/>
        mao,
        
        /// <remarks/>
        map,
        
        /// <remarks/>
        mar,
        
        /// <remarks/>
        mas,
        
        /// <remarks/>
        may,
        
        /// <remarks/>
        mdf,
        
        /// <remarks/>
        mdr,
        
        /// <remarks/>
        men,
        
        /// <remarks/>
        mga,
        
        /// <remarks/>
        mic,
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        mis,
        
        /// <remarks/>
        mkh,
        
        /// <remarks/>
        mlg,
        
        /// <remarks/>
        mlt,
        
        /// <remarks/>
        mnc,
        
        /// <remarks/>
        mni,
        
        /// <remarks/>
        mno,
        
        /// <remarks/>
        moh,
        
        /// <remarks/>
        mon,
        
        /// <remarks/>
        mos,
        
        /// <remarks/>
        mul,
        
        /// <remarks/>
        mun,
        
        /// <remarks/>
        mus,
        
        /// <remarks/>
        mwl,
        
        /// <remarks/>
        mwr,
        
        /// <remarks/>
        myn,
        
        /// <remarks/>
        myv,
        
        /// <remarks/>
        nah,
        
        /// <remarks/>
        nai,
        
        /// <remarks/>
        nap,
        
        /// <remarks/>
        nau,
        
        /// <remarks/>
        nav,
        
        /// <remarks/>
        nbl,
        
        /// <remarks/>
        nde,
        
        /// <remarks/>
        ndo,
        
        /// <remarks/>
        nds,
        
        /// <remarks/>
        nep,
        
        /// <remarks/>
        @new,
        
        /// <remarks/>
        nia,
        
        /// <remarks/>
        nic,
        
        /// <remarks/>
        niu,
        
        /// <remarks/>
        nno,
        
        /// <remarks/>
        nob,
        
        /// <remarks/>
        nog,
        
        /// <remarks/>
        non,
        
        /// <remarks/>
        nor,
        
        /// <remarks/>
        nqo,
        
        /// <remarks/>
        nso,
        
        /// <remarks/>
        nub,
        
        /// <remarks/>
        nwc,
        
        /// <remarks/>
        nya,
        
        /// <remarks/>
        nym,
        
        /// <remarks/>
        nyn,
        
        /// <remarks/>
        nyo,
        
        /// <remarks/>
        nzi,
        
        /// <remarks/>
        oci,
        
        /// <remarks/>
        oji,
        
        /// <remarks/>
        ori,
        
        /// <remarks/>
        orm,
        
        /// <remarks/>
        osa,
        
        /// <remarks/>
        oss,
        
        /// <remarks/>
        ota,
        
        /// <remarks/>
        oto,
        
        /// <remarks/>
        paa,
        
        /// <remarks/>
        pag,
        
        /// <remarks/>
        pal,
        
        /// <remarks/>
        pam,
        
        /// <remarks/>
        pan,
        
        /// <remarks/>
        pap,
        
        /// <remarks/>
        pau,
        
        /// <remarks/>
        peo,
        
        /// <remarks/>
        per,
        
        /// <remarks/>
        phi,
        
        /// <remarks/>
        phn,
        
        /// <remarks/>
        pli,
        
        /// <remarks/>
        pol,
        
        /// <remarks/>
        pon,
        
        /// <remarks/>
        por,
        
        /// <remarks/>
        pra,
        
        /// <remarks/>
        pro,
        
        /// <remarks/>
        pus,
        
        /// <remarks/>
        que,
        
        /// <remarks/>
        raj,
        
        /// <remarks/>
        rap,
        
        /// <remarks/>
        rar,
        
        /// <remarks/>
        roa,
        
        /// <remarks/>
        roh,
        
        /// <remarks/>
        rom,
        
        /// <remarks/>
        rum,
        
        /// <remarks/>
        run,
        
        /// <remarks/>
        rup,
        
        /// <remarks/>
        rus,
        
        /// <remarks/>
        sad,
        
        /// <remarks/>
        sag,
        
        /// <remarks/>
        sah,
        
        /// <remarks/>
        sai,
        
        /// <remarks/>
        sal,
        
        /// <remarks/>
        sam,
        
        /// <remarks/>
        san,
        
        /// <remarks/>
        sas,
        
        /// <remarks/>
        sat,
        
        /// <remarks/>
        scn,
        
        /// <remarks/>
        sco,
        
        /// <remarks/>
        sel,
        
        /// <remarks/>
        sem,
        
        /// <remarks/>
        sga,
        
        /// <remarks/>
        sgn,
        
        /// <remarks/>
        shn,
        
        /// <remarks/>
        sid,
        
        /// <remarks/>
        sin,
        
        /// <remarks/>
        sio,
        
        /// <remarks/>
        sit,
        
        /// <remarks/>
        sla,
        
        /// <remarks/>
        slo,
        
        /// <remarks/>
        slv,
        
        /// <remarks/>
        sma,
        
        /// <remarks/>
        sme,
        
        /// <remarks/>
        smi,
        
        /// <remarks/>
        smj,
        
        /// <remarks/>
        smn,
        
        /// <remarks/>
        smo,
        
        /// <remarks/>
        sms,
        
        /// <remarks/>
        sna,
        
        /// <remarks/>
        snd,
        
        /// <remarks/>
        snk,
        
        /// <remarks/>
        sog,
        
        /// <remarks/>
        som,
        
        /// <remarks/>
        son,
        
        /// <remarks/>
        sot,
        
        /// <remarks/>
        spa,
        
        /// <remarks/>
        srd,
        
        /// <remarks/>
        srn,
        
        /// <remarks/>
        srp,
        
        /// <remarks/>
        srr,
        
        /// <remarks/>
        ssa,
        
        /// <remarks/>
        ssw,
        
        /// <remarks/>
        suk,
        
        /// <remarks/>
        sun,
        
        /// <remarks/>
        sus,
        
        /// <remarks/>
        sux,
        
        /// <remarks/>
        swa,
        
        /// <remarks/>
        swe,
        
        /// <remarks/>
        syc,
        
        /// <remarks/>
        syr,
        
        /// <remarks/>
        tah,
        
        /// <remarks/>
        tai,
        
        /// <remarks/>
        tam,
        
        /// <remarks/>
        tat,
        
        /// <remarks/>
        tel,
        
        /// <remarks/>
        tem,
        
        /// <remarks/>
        ter,
        
        /// <remarks/>
        tet,
        
        /// <remarks/>
        tgk,
        
        /// <remarks/>
        tgl,
        
        /// <remarks/>
        tha,
        
        /// <remarks/>
        tib,
        
        /// <remarks/>
        tig,
        
        /// <remarks/>
        tir,
        
        /// <remarks/>
        tiv,
        
        /// <remarks/>
        tkl,
        
        /// <remarks/>
        tlh,
        
        /// <remarks/>
        tli,
        
        /// <remarks/>
        tmh,
        
        /// <remarks/>
        tog,
        
        /// <remarks/>
        ton,
        
        /// <remarks/>
        tpi,
        
        /// <remarks/>
        tsi,
        
        /// <remarks/>
        tsn,
        
        /// <remarks/>
        tso,
        
        /// <remarks/>
        tuk,
        
        /// <remarks/>
        tum,
        
        /// <remarks/>
        tup,
        
        /// <remarks/>
        tur,
        
        /// <remarks/>
        tut,
        
        /// <remarks/>
        tvl,
        
        /// <remarks/>
        twi,
        
        /// <remarks/>
        tyv,
        
        /// <remarks/>
        udm,
        
        /// <remarks/>
        uga,
        
        /// <remarks/>
        uig,
        
        /// <remarks/>
        ukr,
        
        /// <remarks/>
        umb,
        
        /// <remarks/>
        und,
        
        /// <remarks/>
        urd,
        
        /// <remarks/>
        uzb,
        
        /// <remarks/>
        vai,
        
        /// <remarks/>
        ven,
        
        /// <remarks/>
        vie,
        
        /// <remarks/>
        vol,
        
        /// <remarks/>
        vot,
        
        /// <remarks/>
        wak,
        
        /// <remarks/>
        wal,
        
        /// <remarks/>
        war,
        
        /// <remarks/>
        was,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("wel")]
        wel1,
        
        /// <remarks/>
        wen,
        
        /// <remarks/>
        wln,
        
        /// <remarks/>
        wol,
        
        /// <remarks/>
        xal,
        
        /// <remarks/>
        xho,
        
        /// <remarks/>
        yao,
        
        /// <remarks/>
        yap,
        
        /// <remarks/>
        yid,
        
        /// <remarks/>
        yor,
        
        /// <remarks/>
        ypk,
        
        /// <remarks/>
        zap,
        
        /// <remarks/>
        zbl,
        
        /// <remarks/>
        zen,
        
        /// <remarks/>
        zgh,
        
        /// <remarks/>
        zha,
        
        /// <remarks/>
        znd,
        
        /// <remarks/>
        zul,
        
        /// <remarks/>
        zun,
        
        /// <remarks/>
        zxx,
        
        /// <remarks/>
        zza,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class eventGeschiedenisType {
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        private string typeField;
        
        private string beschrijvingField;
        
        private string verantwoordelijkeFunctionarisField;
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string beschrijving {
            get {
                return this.beschrijvingField;
            }
            set {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string verantwoordelijkeFunctionaris {
            get {
                return this.verantwoordelijkeFunctionarisField;
            }
            set {
                this.verantwoordelijkeFunctionarisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class eventPlanType {
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        private string typeField;
        
        private string beschrijvingField;
        
        private string aanleidingField;
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string beschrijving {
            get {
                return this.beschrijvingField;
            }
            set {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string aanleiding {
            get {
                return this.aanleidingField;
            }
            set {
                this.aanleidingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class relatieType {
        
        private string relatieIDField;
        
        private string typeRelatieField;
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        /// <remarks/>
        public string relatieID {
            get {
                return this.relatieIDField;
            }
            set {
                this.relatieIDField = value;
            }
        }
        
        /// <remarks/>
        public string typeRelatie {
            get {
                return this.typeRelatieField;
            }
            set {
                this.typeRelatieField = value;
            }
        }
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class contextType {
        
        private actorType[] actorField;
        
        private activiteitType[] activiteitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actor")]
        public actorType[] actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activiteit")]
        public activiteitType[] activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class actorType {
        
        private string identificatiekenmerkField;
        
        private string aggregatieniveauField;
        
        private string geautoriseerdeNaamField;
        
        private string[] plaatsField;
        
        private string jurisdictieField;
        
        /// <remarks/>
        public string identificatiekenmerk {
            get {
                return this.identificatiekenmerkField;
            }
            set {
                this.identificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        public string aggregatieniveau {
            get {
                return this.aggregatieniveauField;
            }
            set {
                this.aggregatieniveauField = value;
            }
        }
        
        /// <remarks/>
        public string geautoriseerdeNaam {
            get {
                return this.geautoriseerdeNaamField;
            }
            set {
                this.geautoriseerdeNaamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plaats")]
        public string[] plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
            }
        }
        
        /// <remarks/>
        public string jurisdictie {
            get {
                return this.jurisdictieField;
            }
            set {
                this.jurisdictieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class activiteitType {
        
        private string identificatiekenmerkField;
        
        private string aggregatieniveauField;
        
        private string naamField;
        
        /// <remarks/>
        public string identificatiekenmerk {
            get {
                return this.identificatiekenmerkField;
            }
            set {
                this.identificatiekenmerkField = value;
            }
        }
        
        /// <remarks/>
        public string aggregatieniveau {
            get {
                return this.aggregatieniveauField;
            }
            set {
                this.aggregatieniveauField = value;
            }
        }
        
        /// <remarks/>
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class gebruiksrechtenType {
        
        private string omschrijvingVoorwaardenField;
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        public gebruiksrechtenType() {
            this.omschrijvingVoorwaardenField = "Geen gebruiksrechten";
        }
        
        /// <remarks/>
        public string omschrijvingVoorwaarden {
            get {
                return this.omschrijvingVoorwaardenField;
            }
            set {
                this.omschrijvingVoorwaardenField = value;
            }
        }
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class vertrouwelijkheidType {
        
        private classificatieNiveauType classificatieNiveauField;
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        /// <remarks/>
        public classificatieNiveauType classificatieNiveau {
            get {
                return this.classificatieNiveauField;
            }
            set {
                this.classificatieNiveauField = value;
            }
        }
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public enum classificatieNiveauType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Niet vertrouwelijk")]
        Nietvertrouwelijk,
        
        /// <remarks/>
        Organisatievertrouwelijk,
        
        /// <remarks/>
        Vertrouwelijk,
        
        /// <remarks/>
        Geheim,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Zeer geheim")]
        Zeergeheim,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/ToPX/v2.2")]
    public partial class openbaarheidType {
        
        private string[] omschrijvingBeperkingenField;
        
        private datumOfPeriodeType datumOfPeriodeField;
        
        /// <remarks/>
        // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='Openbaar' attribute on element name='omschrijvingBeperkingen'.
        [System.Xml.Serialization.XmlElementAttribute("omschrijvingBeperkingen")]
        public string[] omschrijvingBeperkingen {
            get {
                return this.omschrijvingBeperkingenField;
            }
            set {
                this.omschrijvingBeperkingenField = value;
            }
        }
        
        /// <remarks/>
        public datumOfPeriodeType datumOfPeriode {
            get {
                return this.datumOfPeriodeField;
            }
            set {
                this.datumOfPeriodeField = value;
            }
        }
    }
}
