//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Noord.Hollands.Archief.Preingest.WebApi.Entities.MDTO.v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    [System.Xml.Serialization.XmlRootAttribute("MDTO", Namespace="https://www.nationaalarchief.nl/mdto", IsNullable=false)]
    public partial class mdtoType {
        
        private objectType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bestand", typeof(bestandType))]
        [System.Xml.Serialization.XmlElementAttribute("informatieobject", typeof(informatieobjectType))]
        public objectType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class bestandType : objectType {
        
        private string omvangField;
        
        private begripGegevens bestandsformaatField;
        
        private checksumGegevens[] checksumField;
        
        private string uRLBestandField;
        
        private verwijzingGegevens isRepresentatieVanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string omvang {
            get {
                return this.omvangField;
            }
            set {
                this.omvangField = value;
            }
        }
        
        /// <remarks/>
        public begripGegevens bestandsformaat {
            get {
                return this.bestandsformaatField;
            }
            set {
                this.bestandsformaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("checksum")]
        public checksumGegevens[] checksum {
            get {
                return this.checksumField;
            }
            set {
                this.checksumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string URLBestand {
            get {
                return this.uRLBestandField;
            }
            set {
                this.uRLBestandField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens isRepresentatieVan {
            get {
                return this.isRepresentatieVanField;
            }
            set {
                this.isRepresentatieVanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class begripGegevens {
        
        private string begripLabelField;
        
        private string begripCodeField;
        
        private verwijzingGegevens begripBegrippenlijstField;
        
        /// <remarks/>
        public string begripLabel {
            get {
                return this.begripLabelField;
            }
            set {
                this.begripLabelField = value;
            }
        }
        
        /// <remarks/>
        public string begripCode {
            get {
                return this.begripCodeField;
            }
            set {
                this.begripCodeField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens begripBegrippenlijst {
            get {
                return this.begripBegrippenlijstField;
            }
            set {
                this.begripBegrippenlijstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class verwijzingGegevens {
        
        private string verwijzingNaamField;
        
        private identificatieGegevens verwijzingIdentificatieField;
        
        /// <remarks/>
        public string verwijzingNaam {
            get {
                return this.verwijzingNaamField;
            }
            set {
                this.verwijzingNaamField = value;
            }
        }
        
        /// <remarks/>
        public identificatieGegevens verwijzingIdentificatie {
            get {
                return this.verwijzingIdentificatieField;
            }
            set {
                this.verwijzingIdentificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class identificatieGegevens {
        
        private string identificatieKenmerkField;
        
        private string identificatieBronField;
        
        /// <remarks/>
        public string identificatieKenmerk {
            get {
                return this.identificatieKenmerkField;
            }
            set {
                this.identificatieKenmerkField = value;
            }
        }
        
        /// <remarks/>
        public string identificatieBron {
            get {
                return this.identificatieBronField;
            }
            set {
                this.identificatieBronField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class checksumGegevens {
        
        private begripGegevens checksumAlgoritmeField;
        
        private string checksumWaardeField;
        
        private System.DateTime checksumDatumField;
        
        /// <remarks/>
        public begripGegevens checksumAlgoritme {
            get {
                return this.checksumAlgoritmeField;
            }
            set {
                this.checksumAlgoritmeField = value;
            }
        }
        
        /// <remarks/>
        public string checksumWaarde {
            get {
                return this.checksumWaardeField;
            }
            set {
                this.checksumWaardeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime checksumDatum {
            get {
                return this.checksumDatumField;
            }
            set {
                this.checksumDatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class beperkingGebruikGegevens {
        
        private begripGegevens beperkingGebruikTypeField;
        
        private string beperkingGebruikNadereBeschrijvingField;
        
        private verwijzingGegevens[] beperkingGebruikDocumentatieField;
        
        private termijnGegevens beperkingGebruikTermijnField;
        
        /// <remarks/>
        public begripGegevens beperkingGebruikType {
            get {
                return this.beperkingGebruikTypeField;
            }
            set {
                this.beperkingGebruikTypeField = value;
            }
        }
        
        /// <remarks/>
        public string beperkingGebruikNadereBeschrijving {
            get {
                return this.beperkingGebruikNadereBeschrijvingField;
            }
            set {
                this.beperkingGebruikNadereBeschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("beperkingGebruikDocumentatie")]
        public verwijzingGegevens[] beperkingGebruikDocumentatie {
            get {
                return this.beperkingGebruikDocumentatieField;
            }
            set {
                this.beperkingGebruikDocumentatieField = value;
            }
        }
        
        /// <remarks/>
        public termijnGegevens beperkingGebruikTermijn {
            get {
                return this.beperkingGebruikTermijnField;
            }
            set {
                this.beperkingGebruikTermijnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class termijnGegevens {
        
        private begripGegevens termijnTriggerStartLooptijdField;
        
        private System.DateTime termijnStartdatumLooptijdField;
        
        private bool termijnStartdatumLooptijdFieldSpecified;
        
        private string termijnLooptijdField;
        
        private string termijnEinddatumField;
        
        /// <remarks/>
        public begripGegevens termijnTriggerStartLooptijd {
            get {
                return this.termijnTriggerStartLooptijdField;
            }
            set {
                this.termijnTriggerStartLooptijdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime termijnStartdatumLooptijd {
            get {
                return this.termijnStartdatumLooptijdField;
            }
            set {
                this.termijnStartdatumLooptijdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool termijnStartdatumLooptijdSpecified {
            get {
                return this.termijnStartdatumLooptijdFieldSpecified;
            }
            set {
                this.termijnStartdatumLooptijdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string termijnLooptijd {
            get {
                return this.termijnLooptijdField;
            }
            set {
                this.termijnLooptijdField = value;
            }
        }
        
        /// <remarks/>
        public string termijnEinddatum {
            get {
                return this.termijnEinddatumField;
            }
            set {
                this.termijnEinddatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class betrokkeneGegevens {
        
        private begripGegevens betrokkeneTypeRelatieField;
        
        private verwijzingGegevens betrokkeneActorField;
        
        /// <remarks/>
        public begripGegevens betrokkeneTypeRelatie {
            get {
                return this.betrokkeneTypeRelatieField;
            }
            set {
                this.betrokkeneTypeRelatieField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens betrokkeneActor {
            get {
                return this.betrokkeneActorField;
            }
            set {
                this.betrokkeneActorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class gerelateerdInformatieobjectGegevens {
        
        private verwijzingGegevens gerelateerdInformatieobjectVerwijzingField;
        
        private begripGegevens gerelateerdInformatieobjectTypeRelatieField;
        
        /// <remarks/>
        public verwijzingGegevens gerelateerdInformatieobjectVerwijzing {
            get {
                return this.gerelateerdInformatieobjectVerwijzingField;
            }
            set {
                this.gerelateerdInformatieobjectVerwijzingField = value;
            }
        }
        
        /// <remarks/>
        public begripGegevens gerelateerdInformatieobjectTypeRelatie {
            get {
                return this.gerelateerdInformatieobjectTypeRelatieField;
            }
            set {
                this.gerelateerdInformatieobjectTypeRelatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class eventGegevens {
        
        private begripGegevens eventTypeField;
        
        private string eventTijdField;
        
        private verwijzingGegevens eventVerantwoordelijkeActorField;
        
        private string eventResultaatField;
        
        /// <remarks/>
        public begripGegevens eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        public string eventTijd {
            get {
                return this.eventTijdField;
            }
            set {
                this.eventTijdField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens eventVerantwoordelijkeActor {
            get {
                return this.eventVerantwoordelijkeActorField;
            }
            set {
                this.eventVerantwoordelijkeActorField = value;
            }
        }
        
        /// <remarks/>
        public string eventResultaat {
            get {
                return this.eventResultaatField;
            }
            set {
                this.eventResultaatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class dekkingInTijdGegevens {
        
        private begripGegevens dekkingInTijdTypeField;
        
        private string dekkingInTijdBegindatumField;
        
        private string dekkingInTijdEinddatumField;
        
        /// <remarks/>
        public begripGegevens dekkingInTijdType {
            get {
                return this.dekkingInTijdTypeField;
            }
            set {
                this.dekkingInTijdTypeField = value;
            }
        }
        
        /// <remarks/>
        public string dekkingInTijdBegindatum {
            get {
                return this.dekkingInTijdBegindatumField;
            }
            set {
                this.dekkingInTijdBegindatumField = value;
            }
        }
        
        /// <remarks/>
        public string dekkingInTijdEinddatum {
            get {
                return this.dekkingInTijdEinddatumField;
            }
            set {
                this.dekkingInTijdEinddatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class raadpleeglocatieGegevens {
        
        private verwijzingGegevens[] raadpleeglocatieFysiekField;
        
        private string[] raadpleeglocatieOnlineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("raadpleeglocatieFysiek")]
        public verwijzingGegevens[] raadpleeglocatieFysiek {
            get {
                return this.raadpleeglocatieFysiekField;
            }
            set {
                this.raadpleeglocatieFysiekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("raadpleeglocatieOnline", DataType="anyURI")]
        public string[] raadpleeglocatieOnline {
            get {
                return this.raadpleeglocatieOnlineField;
            }
            set {
                this.raadpleeglocatieOnlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bestandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(informatieobjectType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class objectType {
        
        private identificatieGegevens[] identificatieField;
        
        private string naamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identificatie")]
        public identificatieGegevens[] identificatie {
            get {
                return this.identificatieField;
            }
            set {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.nationaalarchief.nl/mdto")]
    public partial class informatieobjectType : objectType {
        
        private begripGegevens aggregatieniveauField;
        
        private begripGegevens[] classificatieField;
        
        private string[] trefwoordField;
        
        private string[] omschrijvingField;
        
        private raadpleeglocatieGegevens[] raadpleeglocatieField;
        
        private dekkingInTijdGegevens[] dekkingInTijdField;
        
        private verwijzingGegevens[] dekkingInRuimteField;
        
        private string[] taalField;
        
        private eventGegevens[] eventField;
        
        private begripGegevens waarderingField;
        
        private termijnGegevens bewaartermijnField;
        
        private begripGegevens informatiecategorieField;
        
        private verwijzingGegevens[] isOnderdeelVanField;
        
        private verwijzingGegevens[] bevatOnderdeelField;
        
        private verwijzingGegevens[] heeftRepresentatieField;
        
        private verwijzingGegevens[] aanvullendeMetagegevensField;
        
        private gerelateerdInformatieobjectGegevens[] gerelateerdInformatieobjectField;
        
        private verwijzingGegevens archiefvormerField;
        
        private betrokkeneGegevens[] betrokkeneField;
        
        private verwijzingGegevens activiteitField;
        
        private beperkingGebruikGegevens[] beperkingGebruikField;
        
        /// <remarks/>
        public begripGegevens aggregatieniveau {
            get {
                return this.aggregatieniveauField;
            }
            set {
                this.aggregatieniveauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificatie")]
        public begripGegevens[] classificatie {
            get {
                return this.classificatieField;
            }
            set {
                this.classificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trefwoord")]
        public string[] trefwoord {
            get {
                return this.trefwoordField;
            }
            set {
                this.trefwoordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("omschrijving")]
        public string[] omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("raadpleeglocatie")]
        public raadpleeglocatieGegevens[] raadpleeglocatie {
            get {
                return this.raadpleeglocatieField;
            }
            set {
                this.raadpleeglocatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dekkingInTijd")]
        public dekkingInTijdGegevens[] dekkingInTijd {
            get {
                return this.dekkingInTijdField;
            }
            set {
                this.dekkingInTijdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dekkingInRuimte")]
        public verwijzingGegevens[] dekkingInRuimte {
            get {
                return this.dekkingInRuimteField;
            }
            set {
                this.dekkingInRuimteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taal", DataType="language")]
        public string[] taal {
            get {
                return this.taalField;
            }
            set {
                this.taalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event")]
        public eventGegevens[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        public begripGegevens waardering {
            get {
                return this.waarderingField;
            }
            set {
                this.waarderingField = value;
            }
        }
        
        /// <remarks/>
        public termijnGegevens bewaartermijn {
            get {
                return this.bewaartermijnField;
            }
            set {
                this.bewaartermijnField = value;
            }
        }
        
        /// <remarks/>
        public begripGegevens informatiecategorie {
            get {
                return this.informatiecategorieField;
            }
            set {
                this.informatiecategorieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isOnderdeelVan")]
        public verwijzingGegevens[] isOnderdeelVan {
            get {
                return this.isOnderdeelVanField;
            }
            set {
                this.isOnderdeelVanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bevatOnderdeel")]
        public verwijzingGegevens[] bevatOnderdeel {
            get {
                return this.bevatOnderdeelField;
            }
            set {
                this.bevatOnderdeelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heeftRepresentatie")]
        public verwijzingGegevens[] heeftRepresentatie {
            get {
                return this.heeftRepresentatieField;
            }
            set {
                this.heeftRepresentatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aanvullendeMetagegevens")]
        public verwijzingGegevens[] aanvullendeMetagegevens {
            get {
                return this.aanvullendeMetagegevensField;
            }
            set {
                this.aanvullendeMetagegevensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gerelateerdInformatieobject")]
        public gerelateerdInformatieobjectGegevens[] gerelateerdInformatieobject {
            get {
                return this.gerelateerdInformatieobjectField;
            }
            set {
                this.gerelateerdInformatieobjectField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens archiefvormer {
            get {
                return this.archiefvormerField;
            }
            set {
                this.archiefvormerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("betrokkene")]
        public betrokkeneGegevens[] betrokkene {
            get {
                return this.betrokkeneField;
            }
            set {
                this.betrokkeneField = value;
            }
        }
        
        /// <remarks/>
        public verwijzingGegevens activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("beperkingGebruik")]
        public beperkingGebruikGegevens[] beperkingGebruik {
            get {
                return this.beperkingGebruikField;
            }
            set {
                this.beperkingGebruikField = value;
            }
        }
    }
}
