//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Noord.Hollands.Archief.Preingest.WebApi.Entities.Opex
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    [System.Xml.Serialization.XmlRootAttribute("XIP", Namespace="http://preservica.com/XIP/v6.5", IsNullable=false)]
    public partial class XIPType {
        
        private StructuralObjectType[] structuralObjectField;
        
        private InformationObjectType[] informationObjectField;
        
        private RepresentationType[] representationField;
        
        private ContentObjectType[] contentObjectField;
        
        private GenerationType[] generationField;
        
        private BitstreamType[] bitstreamField;
        
        private IdentifierType[] identifierField;
        
        private LinkType[] linkField;
        
        private RestrictionType[] restrictionField;
        
        private MetadataType[] metadataField;
        
        private EventActionType[] eventActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StructuralObject")]
        public StructuralObjectType[] StructuralObject {
            get {
                return this.structuralObjectField;
            }
            set {
                this.structuralObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformationObject")]
        public InformationObjectType[] InformationObject {
            get {
                return this.informationObjectField;
            }
            set {
                this.informationObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Representation")]
        public RepresentationType[] Representation {
            get {
                return this.representationField;
            }
            set {
                this.representationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentObject")]
        public ContentObjectType[] ContentObject {
            get {
                return this.contentObjectField;
            }
            set {
                this.contentObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Generation")]
        public GenerationType[] Generation {
            get {
                return this.generationField;
            }
            set {
                this.generationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bitstream")]
        public BitstreamType[] Bitstream {
            get {
                return this.bitstreamField;
            }
            set {
                this.bitstreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public IdentifierType[] Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Link")]
        public LinkType[] Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Restriction")]
        public RestrictionType[] Restriction {
            get {
                return this.restrictionField;
            }
            set {
                this.restrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metadata")]
        public MetadataType[] Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventAction")]
        public EventActionType[] EventAction {
            get {
                return this.eventActionField;
            }
            set {
                this.eventActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class StructuralObjectType {
        
        private string refField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string securityTagField;
        
        private string customTypeField;
        
        private string parentField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityTag {
            get {
                return this.securityTagField;
            }
            set {
                this.securityTagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomType {
            get {
                return this.customTypeField;
            }
            set {
                this.customTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class EventType {
        
        private string refField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string userField;
        
        private string workflowNameField;
        
        private long workflowInstanceIdField;
        
        private bool workflowInstanceIdFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string WorkflowName {
            get {
                return this.workflowNameField;
            }
            set {
                this.workflowNameField = value;
            }
        }
        
        /// <remarks/>
        public long WorkflowInstanceId {
            get {
                return this.workflowInstanceIdField;
            }
            set {
                this.workflowInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkflowInstanceIdSpecified {
            get {
                return this.workflowInstanceIdFieldSpecified;
            }
            set {
                this.workflowInstanceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class EventActionType {
        
        private EventType eventField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string entityField;
        
        private string serialisedCommandField;
        
        private string commandTypeField;
        
        /// <remarks/>
        public EventType Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public string SerialisedCommand {
            get {
                return this.serialisedCommandField;
            }
            set {
                this.serialisedCommandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commandType {
            get {
                return this.commandTypeField;
            }
            set {
                this.commandTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class MetadataType {
        
        private string refField;
        
        private string entityField;
        
        private System.Xml.XmlElement contentField;
        
        private string schemaUriField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemaUri {
            get {
                return this.schemaUriField;
            }
            set {
                this.schemaUriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class RestrictionType {
        
        private restrictionType typeField;
        
        private string entityField;
        
        /// <remarks/>
        public restrictionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public enum restrictionType {
        
        /// <remarks/>
        LOCK,
        
        /// <remarks/>
        DELETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class LinkType {
        
        private string typeField;
        
        private string fromEntityField;
        
        private string toEntityField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string FromEntity {
            get {
                return this.fromEntityField;
            }
            set {
                this.fromEntityField = value;
            }
        }
        
        /// <remarks/>
        public string ToEntity {
            get {
                return this.toEntityField;
            }
            set {
                this.toEntityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class IdentifierType {
        
        private string apiIdField;
        
        private string typeField;
        
        private string valueField;
        
        private string entityField;
        
        /// <remarks/>
        public string ApiId {
            get {
                return this.apiIdField;
            }
            set {
                this.apiIdField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class FixityType {
        
        private fixityType fixityAlgorithmRefField;
        
        private string fixityValueField;
        
        /// <remarks/>
        public fixityType FixityAlgorithmRef {
            get {
                return this.fixityAlgorithmRefField;
            }
            set {
                this.fixityAlgorithmRefField = value;
            }
        }
        
        /// <remarks/>
        public string FixityValue {
            get {
                return this.fixityValueField;
            }
            set {
                this.fixityValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public enum fixityType {
        
        /// <remarks/>
        MD5,
        
        /// <remarks/>
        SHA1,
        
        /// <remarks/>
        SHA256,
        
        /// <remarks/>
        SHA512,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class BitstreamType {
        
        private string filenameField;
        
        private long fileSizeField;
        
        private string containerField;
        
        private string extractionToolField;
        
        private string extractionToolParamsField;
        
        private string physicalLocationField;
        
        private string physicalFilenameField;
        
        private string originalFilenameField;
        
        private FixityType[] fixitiesField;
        
        /// <remarks/>
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public string Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        /// <remarks/>
        public string ExtractionTool {
            get {
                return this.extractionToolField;
            }
            set {
                this.extractionToolField = value;
            }
        }
        
        /// <remarks/>
        public string ExtractionToolParams {
            get {
                return this.extractionToolParamsField;
            }
            set {
                this.extractionToolParamsField = value;
            }
        }
        
        /// <remarks/>
        public string PhysicalLocation {
            get {
                return this.physicalLocationField;
            }
            set {
                this.physicalLocationField = value;
            }
        }
        
        /// <remarks/>
        public string PhysicalFilename {
            get {
                return this.physicalFilenameField;
            }
            set {
                this.physicalFilenameField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalFilename {
            get {
                return this.originalFilenameField;
            }
            set {
                this.originalFilenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Fixity", IsNullable=false)]
        public FixityType[] Fixities {
            get {
                return this.fixitiesField;
            }
            set {
                this.fixitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class GenerationPropertyType {
        
        private string groupField;
        
        private string pUIDField;
        
        private string propertyNameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class GenerationFormatType {
        
        private string pUIDField;
        
        private short priorityField;
        
        private identificationMethod identificationMethodField;
        
        private string formatNameField;
        
        private string formatVersionField;
        
        private string warningsField;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
        
        /// <remarks/>
        public short Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public identificationMethod IdentificationMethod {
            get {
                return this.identificationMethodField;
            }
            set {
                this.identificationMethodField = value;
            }
        }
        
        /// <remarks/>
        public string FormatName {
            get {
                return this.formatNameField;
            }
            set {
                this.formatNameField = value;
            }
        }
        
        /// <remarks/>
        public string FormatVersion {
            get {
                return this.formatVersionField;
            }
            set {
                this.formatVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public enum identificationMethod {
        
        /// <remarks/>
        Container,
        
        /// <remarks/>
        Signature,
        
        /// <remarks/>
        Extension,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class GenerationType {
        
        private string contentObjectField;
        
        private string labelField;
        
        private string formatGroupField;
        
        private System.DateTime effectiveDateField;
        
        private bool effectiveDateFieldSpecified;
        
        private string[] bitstreamsField;
        
        private GenerationFormatType[] formatsField;
        
        private GenerationPropertyType[] propertiesField;
        
        private bool originalField;
        
        private bool originalFieldSpecified;
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        /// <remarks/>
        public string ContentObject {
            get {
                return this.contentObjectField;
            }
            set {
                this.contentObjectField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string FormatGroup {
            get {
                return this.formatGroupField;
            }
            set {
                this.formatGroupField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveDateSpecified {
            get {
                return this.effectiveDateFieldSpecified;
            }
            set {
                this.effectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bitstream", IsNullable=false)]
        public string[] Bitstreams {
            get {
                return this.bitstreamsField;
            }
            set {
                this.bitstreamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Format", IsNullable=false)]
        public GenerationFormatType[] Formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public GenerationPropertyType[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool original {
            get {
                return this.originalField;
            }
            set {
                this.originalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalSpecified {
            get {
                return this.originalFieldSpecified;
            }
            set {
                this.originalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class ContentObjectType {
        
        private string refField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string securityTagField;
        
        private string customTypeField;
        
        private string parentField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityTag {
            get {
                return this.securityTagField;
            }
            set {
                this.securityTagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomType {
            get {
                return this.customTypeField;
            }
            set {
                this.customTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class RepresentationPropertyType {
        
        private string groupField;
        
        private string pUIDField;
        
        private string propertyNameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class RepresentationFormatType {
        
        private string pUIDField;
        
        private string formatNameField;
        
        private short priorityField;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
        
        /// <remarks/>
        public string FormatName {
            get {
                return this.formatNameField;
            }
            set {
                this.formatNameField = value;
            }
        }
        
        /// <remarks/>
        public short Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class RepresentationType {
        
        private string informationObjectField;
        
        private string nameField;
        
        private string typeField;
        
        private string[] contentObjectsField;
        
        private RepresentationFormatType[] representationFormatsField;
        
        private RepresentationPropertyType[] representationPropertiesField;
        
        /// <remarks/>
        public string InformationObject {
            get {
                return this.informationObjectField;
            }
            set {
                this.informationObjectField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContentObject", IsNullable=false)]
        public string[] ContentObjects {
            get {
                return this.contentObjectsField;
            }
            set {
                this.contentObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RepresentationFormat", IsNullable=false)]
        public RepresentationFormatType[] RepresentationFormats {
            get {
                return this.representationFormatsField;
            }
            set {
                this.representationFormatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RepresentationProperty", IsNullable=false)]
        public RepresentationPropertyType[] RepresentationProperties {
            get {
                return this.representationPropertiesField;
            }
            set {
                this.representationPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://preservica.com/XIP/v6.5")]
    public partial class InformationObjectType {
        
        private string refField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string securityTagField;
        
        private string customTypeField;
        
        private string parentField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityTag {
            get {
                return this.securityTagField;
            }
            set {
                this.securityTagField = value;
            }
        }
        
        /// <remarks/>
        public string CustomType {
            get {
                return this.customTypeField;
            }
            set {
                this.customTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
}
